= NOTE
:toc:
:icons: font

== Anotation

// [cols=3*] 컬럼 지정
// [%header,format=csv] 테이블 포맷팅변환
// [cols="1,5a,1"] 컬럼 너비지정 및 asciidoc 컨텐츠 추가(a)

=== Controller
[cols="1,5,1"]
.Controller
|===
| 이름 | 용도 | 경로

| @Controller
| 해당 어노테이션의 클래스가 컨트롤러의 기능을 수행
| org.springframework.stereotype.Controller

| @GetMapping(`URL명`)
| 위 경로로 URL요청이 발생하면 해당 어노테이션의 메서드가 실행, 경로와 메서드를 매핑footnote:[URL명과 메서드명은 동일할 필요는 없다]footnote:[Get방식의 요청은 GetMapping, Post방식의 요청은 PostMapping]
| org.springframework.web.bind.annotation.GetMapping

| @ResponseBody
| return body 만들어서 보낼때 사용
| org.springframework.web.bind.annotation.ResponseBody

| @Getterfootnoteref:[lombok,required: lombok]
| Getter 메서드를 추가하지않아도 `get변수명`(파스칼표기)을 사용할수있다.
| lombok.Getter

| @Setterfootnoteref:[lombok]
| Setter 메서드를 추가하지않아도 `set변수명`(파스칼표기) 사용할수있다.
| lombok.Setter

| @RequiredArgsConstructor footnoteref:[lombok]
| 해당 속성을 필요로하는 생성자가 롬복에 의해 자동으로 생성된다._**(final이 없는 속성은 생성자에 포함되지않는다.)**_
| lombok.RequiredArgsConstructor


|===

== Library
Spring Boot Devtools::
* 서버 재시작 없이도 코드변경사항을 적용해준다.
* dependencies
** developmentOnly 'org.springframework.boot:spring-boot-devtools'

lombok(롬복)footnote:[plugin설치,File->Settings->Build,Exceution,Deployment->Compiler+->Annotation Processors에서 Enable annotation processing 체크]::
* 자바 클래스에 Getter, Setter, 생성자 등을 자동으로 만들어주는도구이다.
* dependencies
** compileOnlyfootnote:[해당 라이브러리가 컴파일 단계에서만 필요한 경우에 사용한다.] 'org.projectlombok:lombok'
** annotationProcessorfootnote:[컴파일 단계에서 어노테이션을 분석하고 처리하기 위해 사용한다.] 'org.projectlombok:lombok'


== Struct

src/main/java 디렉터리::
link:src/main/java/[src/main/java 디렉터리]의 `com.mysite.sbb` 패키지는 **자바파일을 작성하는 공간**이다. +
자바 파일로는 link:src/main/java/com/example/sbb/HelloController.java[HelloController]와 같은 스프링부트의 *컨트롤러*, *폼과 DTO*, *데이터베이스 처리를 위한 엔티티*, *서비스 파일* 등이있다.


SbbApplication.java 파일::
시작을 담당하는 파일이다. link:src/main/java/com/example/sbb/SbbApplication.java[<프로젝트명>+Application.java] +
스프링부트 프로젝트를 생성할때 "Sbb"라는 이름을 사용하면 다음과같은 SbbApplication.java 파일이 자동으로 생성된다.

[source,java]
----
package com.mysite.sbb;

import org.springframework.boot.SpringAcpplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SbbApplication {

    public static void main(String[] args) {
        SpringApplication.run(SbbApplication.class, args);
    }
}
----
SbbApplication 클래스에는 위와 같이 반드시 `@SpringBootApplication` 어노테이션이 적용되어야한다. +
@SpringBootApplication 어노테이션을 통해 스프링부트의 모든 설정이 관리된다.

src/main/resources 디렉터리::
link:src/main/resources[src/main/resource 디렉터리]는 자바 파일을 제외한 HTML, CSS, Javascript, 환경파일 등을 작성하는 공간이다.

templates 디렉터리::
link:src/main/resources/templates/[src/main/resources/templates 디렉터리]에는 템플릿 파일을 저장한다. +
템플릿 파일은 HTML 파일 형태로 자바 객체와 연동되는 파일이다. +
templates 디렉터리에는 SBB의 질문 목록, 질문 상세등의 HTML 파일을 저장한다.

static 디렉터리::
link:src/main/resources/static/[static 디렉터리]는 SBB 프로젝트의 스트일시트(.css) 자바 스크립트(.js) 그리고 이미지 파일 (.jpg, png) 등을 저장하는 공간이다.

application.properties 파일::
application.properties 파일은 SBB 프로젝트의 환경을 설정한다. SBB 프로젝트의 환경, 데이터베이스 등의 설정을 이파일에 저장한다.

src/test/java 디렉터리::
link:src/test/java/[src/test/java 디렉터리]는 SBB 프로젝트에서 작성한 파일을 테스트하기 위한 테스트 코드를 작성하는 공간이다. +
JUint과 스프링부트의 테스팅 도구를 사용하여 서버를 실행하지 않은 상태에서 src/main/java 디렉터리에 작성한 코드를 테스트할 수 있다.

build.gradle 파일::
그레이들(Gradle)이 사용하는 환경 파일이다. 그레이들은 그루비(Groovy)를 기반으로 한 빌드 도구로 Ant, Maven과 가은 이전 세대 빌드 도구의 단점을 보완하고 장점을 취합하여 만든 빌드 도구이다. build.gradle 파일에는 프로젝트를 위해 필요한 플러그인과 라이브러리 등을 기술한다.

NOTE: 나머지 디텍터리와 파일등은 자동 생성되거나 크게 중요하지 않은 것들이라 생략
